=== muammar1109/Q2A20171X/kuisamr.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Banksoal">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="soal"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="soal">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="mk"/>
                <xs:element ref="dosen"/>
                <xs:element ref="tipe"/>
                <xs:element ref="kode"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="mk">
    	<xs:simpleType>
    		<xs:restriction base="xs:integer">
    			<xs:minExclusive value="1"></xs:minExclusive>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="dosen">
    	<xs:simpleType>
    		<xs:restriction base="xs:NCName">
    			<xs:minLength value="1"></xs:minLength>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="tipe">
    	<xs:simpleType>
    		<xs:restriction base="xs:NCName">
    			<xs:minLength value="1"></xs:minLength>
    			<xs:pattern value="essay"></xs:pattern>
    			<xs:pattern value="pilganda"></xs:pattern>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="kode">
    	<xs:simpleType>
    		<xs:restriction base="xs:string">
    			<xs:minLength value="1"></xs:minLength>
    			<xs:pattern value="PRAK/MK11/JK678"></xs:pattern>
    			<xs:pattern value="TEO/MK34/AB222"></xs:pattern>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
</xs:schema>

=== muammar1109/Q2A20171X/Kuisamr.xml
<?xml version="1.0" encoding="UTF-8"?>
<Banksoal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="kuisamr.xsd">
	<soal>
		<mk>12</mk>
		<dosen>Anjas</dosen>
		<tipe>essay</tipe>
		<kode>PRAK/MK11/JK678</kode>
	</soal>
	<soal>
		<mk>13</mk>
		<dosen>Nuraini</dosen>
		<tipe>pilganda</tipe>
		<kode>TEO/MK34/AB222</kode>
	</soal>
</Banksoal>
